title:
#include "sprites/title.bmp"

player_man_back_sprite:
#include "sprites/player_man_back.bmp"

player_woman_back_sprite:
#include "sprites/player_woman_back.bmp"

player_down_sprite:
#include "sprites/player_down01.bmp"
#include "sprites/player_down02.bmp"
#include "sprites/player_down03.bmp"

player_man_left_sprite:
#include "sprites/player_man_left01.bmp"
#include "sprites/player_man_left02.bmp"
#include "sprites/player_man_left03.bmp"

player_man_right_sprite:
#include "sprites/player_man_right01.bmp"
#include "sprites/player_man_right02.bmp"
#include "sprites/player_man_right03.bmp"

player_man_up_sprite:
#include "sprites/player_man_up01.bmp"
#include "sprites/player_man_up02.bmp"
#include "sprites/player_man_up03.bmp"

player_woman_left_sprite:
#include "sprites/player_woman_left01.bmp"
#include "sprites/player_woman_left02.bmp"
#include "sprites/player_woman_left03.bmp"

player_woman_right_sprite:
#include "sprites/player_woman_right01.bmp"
#include "sprites/player_woman_right02.bmp"
#include "sprites/player_woman_right03.bmp"

player_woman_up_sprite:
#include "sprites/player_woman_up01.bmp"
#include "sprites/player_woman_up02.bmp"
#include "sprites/player_woman_up03.bmp"

opponent_man_sprite:
#include "sprites/opponent_man.bmp"

opponent_woman_sprite:
#include "sprites/opponent_woman.bmp"

cursor_sprite:
#include "sprites/cursor.bmp"

scroll_cursor_sprite:
#include "sprites/scroll_cursor.bmp"

battle_bar:
#include "sprites/battle_bar.bmp"

pokeball_pokemon_alread_captured:
#include "sprites/pokeball_pokemon_already_captured.bmp"

pokeball_pokemon_alive:
#include "sprites/pokeball_pokemon_alive.bmp"

pokeball_pokemon_dead:
#include "sprites/pokeball_pokemon_dead.bmp"

pokeball_sprite:
#include "sprites/pokeball.bmp"
